package com.suning.vgs.lifesquare.autotool.util;

public enum SupportedCellColors {
	BLACK,WHITE,RED,BRIGHT_GREEN,BLUE,YELLOW,PINK,TURQUOISE,DARK_RED,GREEN,DARK_BLUE,DARK_YELLOW,VIOLET
	,TEAL,GREY_25_PERCENT,GREY_50_PERCENT,CORNFLOWER_BLUE,MAROON,LEMON_CHIFFON,ORCHID,CORAL,ROYAL_BLUE
	,LIGHT_CORNFLOWER_BLUE,SKY_BLUE,LIGHT_TURQUOISE,LIGHT_GREEN,LIGHT_YELLOW,PALE_BLUE,ROSE,LAVENDER,TAN
	,LIGHT_BLUE,AQUA,LIME,GOLD,LIGHT_ORANGE,ORANGE,BLUE_GREY,GREY_40_PERCENT,DARK_TEAL,SEA_GREEN,DARK_GREEN
	,OLIVE_GREEN,BROWN,PLUM,INDIGO,GREY_80_PERCENT;
}
